### PR TITLE
Changed title and added logos

### LINKED ISSUE #47: [Frontend] Add favicon and change website title
## Summary
Update the favicon to the website icon, change the title from `Create Next App` to `Smart Ryokou`

### PR DESCRIPTION
**Pull request by YadanarLin**

### CODE REVIEW

**Comment by chanon-mike** [comment]
Seems like the icon is not updated yet. Can you make the icon be our website icon?
image

**Comment by YadanarLin** [comment]
sorry, how about now?

**Comment by chanon-mike** [comment]
image

Please remove the white background and make all the icon transparent

**Comment by YadanarLin** [comment]
I have fixed the main logo but for the other two, the files got locked or something and I cannot commit so I will do it together with another issue. Is that okay?

**Comment by chanon-mike** [comment]
@YadanarLin sry for late review, yep that's ok for now

**Review by chanon-mike — APPROVED** [review]

**Pull request merged**
