### PR TITLE
Add directions with color

### LINKED ISSUE #106: [Google Maps] Route direction for each date
## Background
We got many feedbacks of to make the route direction for each location in map

## Summary
Add route direction for each location for each date
- For example, default display is date 1 route
- When click in date 2's location, display route for date 2 instead

### PR DESCRIPTION
**Pull request by phattd15**

### CODE REVIEW

**Review by chanon-mike — CHANGES_REQUESTED** [review]
Thank for your work!

I think the arrow line is too narrow and head is too big. Can you make it so that it is more balance and easier to see?

Also, I think the yellow color is kinda difficult to see, so it would be great if you can change the color in someway. 

image

**Review by chanon-mike — COMMENTED** [review]
The implementation itself is fine. But do you think there are the way to make it easier to look? 
What is your comment on this? Is it look too busy? Do you think we should still have this feature?

image

**Comment by chanon-mike** [comment]
@phattd15 
Toggle button is hard to see (I cannot find it for 10 seconds) and in mobile, it is floating by itself
image

I will try fix the design.

**Review by student158 — APPROVED** [review]
LGTM!

**Review by chanon-mike — APPROVED** [review]

**Pull request merged**
